from tkinter import *
def count_window():
    def convert_base(num, to_base, from_base):
        n = int(num, from_base) if isinstance(num, str) else num
        alphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        res = ""
        while n > 0:
            n, m = divmod(n, to_base)
            res += alphabet[m]
        resu = "Результат перевода: " + inpnum.get() + " в " + basefrom.get() + "-ной системе счисления" + " = " + res[::-1] + " в " + baseto.get() + "-ной системе счисления"
        out_text.configure(text=resu)
        return res[::-1]
    def go_back():
        window.destroy()
        main_window()
    def convert():
        convert_base(inpnum.get(), int(baseto.get()), int(basefrom.get()))
    window = Tk()
    window.geometry('1100x500')
    window.title("Перевод из одной сиситемы счисления в другую")
    lbl = Label(window, text="Перевести из системы счисления с основанием:", font=("Arial Bold", 14))
    lbl.grid(column=0, row=0)
    basefrom = Entry(window,width=10)
    basefrom.grid(column=1, row=0)
    basefrom.insert(0,"10")
    lbl = Label(window, text="в сиситему счисления с основанием:", font=("Arial Bold", 14))
    lbl.grid(column=2, row=0)
    baseto = Entry(window,width=10, text="2")
    baseto.grid(column=3, row=0)
    baseto.insert(0,"2")
    lbl = Label(window, text="Число:", font=("Arial Bold", 14))
    lbl.grid(column=0, row=1)
    inpnum = Entry(window,width=30)
    inpnum.grid(column=1, row=1)
    btn = Button(window, text="Перевести", command=convert)
    btn.grid(column=1, row=2)
    out_text = Label(window, text="Результат перевода: ", font=("Arial Bold", 15))
    out_text.place(x=75, y=85)
    backbtn = Button(window, text="В главное меню", command=go_back, height=4, width=20)
    backbtn.place(x=5, y=425)
    window.mainloop()
def main_window():
    def open_convert():
        window.destroy()
        count_window()
    def open_education():
        window.destroy()
        education_window()
    window = Tk()
    window.geometry('1100x500')
    window.title("Главное меню")
    lbl = Label(window, text="Это программа по обученю по переводу чисел в разные системы счисления", font=("Arial Bold", 14))
    lbl.grid(column=0, row=0)
    lbl = Label(window, text="и проверки перевода в них", font=("Arial Bold", 14))
    lbl.grid(column=0, row=1)
    btn = Button(window, text="Обучение", command=open_education ,font=("Arial Bold", 14), height = 5, width = 20)
    btn.place(x=125, y=85)
    btn = Button(window, text="Перевод", command=open_convert, font=("Arial Bold", 14), height = 5, width = 20)
    btn.place(x=400, y=85)
    window.mainloop()
def education_window():
    def go_back():
        window.destroy()
        main_window()
    def open_education_2():
        window.destroy()
        education_window_2()
    def open_education_8():
        window.destroy()
        education_window_8()
    def open_education_10():
        window.destroy()
        education_window_10()
    def open_education_16():
        window.destroy()
        education_window_16()
    window = Tk()
    window.geometry('1100x500')
    window.title("Обучение переводу")
    lbl = Label(window, text="Выберите в какую систему счисления вы хотите научиться перводить", font=("Arial Bold", 14))
    lbl.grid(column=0, row=0)
    btn2 = Button(window, text="В двоичную",command=open_education_2, font=("Arial Bold", 14), height = 5, width = 20)
    btn2.grid(column=0, row=1)
    btn8 = Button(window, text="В восьмеричную",command=open_education_8, font=("Arial Bold", 14), height = 5, width = 20)
    btn8.grid(column=0, row=2)
    btn10 = Button(window, text="В десятичную",command=open_education_10, font=("Arial Bold", 14), height = 5, width = 20)
    btn10.grid(column=1, row=1)
    btn16 = Button(window, text="В шестнадцатиричную",command=open_education_16, font=("Arial Bold", 14), height=5, width=20)
    btn16.grid(column=1, row=2)
    backbtn = Button(window, text="В главное меню", command=go_back, height=4, width=20)
    backbtn.place(x=5, y=425)
    window.mainloop()
def education_window_2():
    def go_back():
        window.destroy()
        main_window()
    window = Tk()
    window.geometry('1200x800')
    window.title("Обучение переводу в двоиную систему счисления")
    frame = Frame(window)
    frame.place(x=25, y=5)
    canvas = Canvas(window, height=700, width=1150)
    img = PhotoImage(file='2_1.png')
    image = canvas.create_image(0, 0, anchor='nw', image=img)
    canvas.place(x=25, y=5)
    backbtn = Button(window, text="В главное меню", command=go_back, height=4, width=20)
    backbtn.place(x=5, y=725)
    window.mainloop()
def education_window_8():
    def go_back():
        window.destroy()
        main_window()
    window = Tk()
    window.geometry('1200x800')
    window.title("Обучение переводу в двоиную систему счисления")
    frame = Frame(window)
    frame.place(x=25, y=5)
    canvas = Canvas(window, height=700, width=1150)
    img = PhotoImage(file='8_1.png')
    image = canvas.create_image(0, 0, anchor='nw', image=img)
    canvas.place(x=25, y=5)
    backbtn = Button(window, text="В главное меню", command=go_back, height=4, width=20)
    backbtn.place(x=5, y=725)
    window.mainloop()
def education_window_10():
    def go_back():
        window.destroy()
        main_window()
    window = Tk()
    window.geometry('1200x800')
    window.title("Обучение переводу в двоиную систему счисления")
    frame = Frame(window)
    frame.place(x=25, y=5)
    canvas = Canvas(window, height=700, width=1150)
    img = PhotoImage(file='10_1.png')
    image = canvas.create_image(0, 0, anchor='nw', image=img)
    canvas.place(x=25, y=5)
    backbtn = Button(window, text="В главное меню", command=go_back, height=4, width=20)
    backbtn.place(x=5, y=725)
    window.mainloop()
def education_window_16():
    def go_back():
        window.destroy()
        main_window()
    window = Tk()
    window.geometry('1200x800')
    window.title("Обучение переводу в двоиную систему счисления")
    frame = Frame(window)
    frame.place(x=25, y=5)
    canvas = Canvas(window, height=700, width=1150)
    img = PhotoImage(file='16_1.png')
    image = canvas.create_image(0, 0, anchor='nw', image=img)
    canvas.place(x=25, y=5)
    backbtn = Button(window, text="В главное меню", command=go_back, height=4, width=20)
    backbtn.place(x=5, y=725)
    window.mainloop()
main_window()